# Default values for app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

meta:
  env: ""
  version: ""
  maintainer: ""

image:
  repository: ""
  tag: latest

  pullPolicy: IfNotPresent

  pullSecrets: []

configMap:
  enabled: true

  annotations: {}

  mountPath: params

  subPath: ""

  readOnly: true

  data: {}

server:
  enabled: true

  nameOverride: ""
  fullNameOverride: ""

  annotations: {}

  autoReload: true

  replicas: 1

  rollingUpdate:
    maxSurge: 25%
    maxUnavailable: 25%

  command: []
  args: []

  port: 80

  prometheus:
    scrape: true
    path: /metrics
    port: 2112

  istio:
    injected: false

  liveness:
    enabled: true
    delay: 10
    period: 10
    timeout: 3
    failure: 3

  readiness:
    enabled: true
    path: /healthz
    delay: 5
    period: 10
    timeout: 3
    success: 1
    failure: 3

  resources: {}

  env: []

  restartPolicy: Always

  dnsPolicy: ClusterFirst

  nodeSelector: {}

  tolerations: []

  affinity: {}

worker:
  enabled: false

  nameOverride: ""
  fullNameOverride: ""

  annotations: {}

  autoReload: true

  replicas: 1

  rolling:
    surge: 25%
    unavailable: 25%

  command: []
  args: []

  prometheus:
    scrape: true
    path: /metrics
    port: 2112

  istio:
    injected: false

  liveness:
    enabled: false
    delay: 10
    period: 10
    timeout: 3
    failure: 3
    command:
      - rm
      - /tmp/healthz

  resources: {}

  env: []

  restartPolicy: Always

  dnsPolicy: ClusterFirst

  nodeSelector: {}

  tolerations: []

  affinity: {}

service:
  enabled: true

  annotations: {}

  type: ClusterIP

  port: 80

ingress:
  enabled: true

  annotations: {}

  class: nginx

  tls:
    - hosts: []

  hosts: []

  issuer: letsencrypt

virtualService:
  enabled: false

  gateways: []

  hosts: []

  routes: []


autoscaling:
  enabled: true

  annotations: {}

  minReplicas: 1
  maxReplicas: 3

  cpu:
    targetAverageUtilization: 85
  memory:
    targetAverageUtilization: 85

debugger:
  enabled: false

  nameOverride: ""

  annotations: {}

  replicas: 1

  image:
    repository: zackijack/k1p
    tag: latest

    pullPolicy: Always

    pullSecrets: []

  command: []

  istio:
    injected: false

  resources: {}

  env: []

  restartPolicy: Always

  dnsPolicy: ClusterFirst

  nodeSelector: {}

  tolerations: []

  affinity: {}
