{{- if and (ne .Values.meta.env "prod") .Values.debugger.enabled -}}
{{- $fullName := include "debugger.name" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.debugger.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  replicas: {{ .Values.debugger.replicas }}
  selector:
    matchLabels:
      name: {{ $fullName }}
      env: {{ .Values.meta.env }}
  template:
    metadata:
      labels:
        name: {{ $fullName }}
        env: {{ .Values.meta.env }}
        version: {{ .Values.meta.version }}
        maintainer: {{ .Values.meta.maintainer }}
        managed-by: {{ .Release.Service }}
        helm-chart: {{ include "meta.chart" . }}
      annotations:
        sidecar.istio.io/inject: {{ .Values.debugger.istio.injected | quote }}
    spec:
      {{- with .Values.debugger.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ $fullName }}
          image: "{{ .Values.debugger.image.repository }}:{{ .Values.debugger.image.tag }}"
          imagePullPolicy: {{ .Values.debugger.image.pullPolicy }}
          {{- with .Values.debugger.command }}
          command:
            {{- range . }}
            - {{ . | quote }}
            {{- end }}
          {{- end }}
          resources:
            {{- toYaml .Values.debugger.resources | nindent 12 }}
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            {{- with .Values.debugger.env }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
      restartPolicy: {{ .Values.debugger.restartPolicy }}
      dnsPolicy: {{ .Values.debugger.dnsPolicy }}
      {{- with .Values.debugger.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.debugger.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.debugger.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
