{{- if .Values.worker.enabled -}}
{{- $name := .Release.Name -}}
{{- $fullName := include "worker.name" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.worker.autoReload }}
    reloader.stakater.com/auto: "true"
    {{- end }}
    {{- with .Values.worker.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  replicas: {{ .Values.worker.replicas }}
  selector:
    matchLabels:
      name: {{ $fullName }}
      env: {{ .Values.meta.env }}
  {{- with .Values.worker.rolling }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: {{ .surge }}
      maxUnavailable: {{ .unavailable }}
  {{- end }}
  template:
    metadata:
      labels:
        name: {{ $fullName }}
        env: {{ .Values.meta.env }}
        version: {{ .Values.meta.version }}
        maintainer: {{ .Values.meta.maintainer }}
        managed-by: {{ .Release.Service }}
        helm-chart: {{ include "meta.chart" . }}
      annotations:
        prometheus.io/scrape: {{ .Values.worker.prometheus.scrape | quote }}
        {{- if .Values.worker.prometheus.scrape }}
        prometheus.io/path: {{ .Values.worker.prometheus.path | quote }}
        {{- with .Values.worker.prometheus.port }}
        prometheus.io/port: {{ . | quote }}
        {{- end }}
        {{- end }}
        sidecar.istio.io/inject: {{ .Values.worker.istio.injected | quote }}
    spec:
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ $fullName }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.worker.command }}
          command:
            {{- range . }}
            - {{ . | quote }}
            {{- end }}
          {{- end }}
          {{- with .Values.worker.args }}
          args:
            {{- range . }}
            - {{ . | quote }}
            {{- end }}
          {{- end }}
          {{- if and .Values.worker.prometheus.scrape .Values.worker.prometheus.port }}
          ports:
            - name: prometheus
              containerPort: {{ .Values.worker.prometheus.port }}
              protocol: TCP
          {{- end }}
          {{- if .Values.worker.liveness.enabled }}
          livenessProbe:
            exec:
              command:
                {{- range .Values.worker.liveness.command }}
                - {{ . | quote }}
                {{- end }}
            initialDelaySeconds: {{ .Values.worker.liveness.delay }}
            periodSeconds: {{ .Values.worker.liveness.period }}
            timeoutSeconds: {{ .Values.worker.liveness.timeout }}
            failureThreshold: {{ .Values.worker.liveness.failure }}
          {{- end }}
          resources:
            {{- toYaml .Values.worker.resources | nindent 12 }}
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            {{- with .Values.worker.env }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- if .Values.configMap.enabled }}
          volumeMounts:
            - name: {{ $fullName }}
              mountPath: {{ .Values.configMap.mountPath }}
              readOnly: {{ .Values.configMap.readOnly }}
          {{- end }}
      {{- if .Values.configMap.enabled }}
      volumes:
        - name: {{ $fullName }}
          configMap:
            name: {{ $name }}
      {{- end }}
      restartPolicy: {{ .Values.worker.restartPolicy }}
      dnsPolicy: {{ .Values.worker.dnsPolicy }}
      {{- with .Values.worker.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.worker.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.worker.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
